### ISSUE TITLE
Provide method to retrieve all emojis at once

### ISSUE THREAD

**Issue by dsentker** [jawira/emoji-catalog#10]
Thanks for your work. I would suggest to add a static method to get all emojis at once.

Quick & dirty example:

```php
public static function all(): array {
    return (new \ReflectionClass(__CLASS__))->getConstants();
}
```

**Comment by jawira** [comment]
Hello :), do you need this functionality or it's just a suggestion?

**Comment by dsentker** [comment]
It's just a suggestion :)

**Comment by jawira** [comment]
I will keep your suggestion in mind. The thing is I want this library to be as simple as possible (one class with constants only), but I'm thinking about creating another project with all this additional functionalities, "emoji-toolbox" or something like that. 
Thank you for your suggestion and your code snippet 👍
