### ISSUE TITLE
Data Source broken

### ISSUE THREAD

**Issue by PaulWoitaschek** [jawira/emoji-catalog#19]
I do believe that using the html emoji list for an import is wrong.

https://unicode.org/emoji/charts/full-emoji-list.html

For example for mountain, it generates `U+26F0` which is not fully qualified and do causes a black triangle to be shown in some fonts.

Instead, I recommend to use the raw data instead of parsing the html file:

https://unicode.org/Public/emoji/14.0/emoji-sequences.txt

This would lead to the correct code points being generated, in this case:
```
26F0 FE0F     ; Basic_Emoji                  ; mountain                                                       # E0.7   [1] (⛰️)
```

**Comment by jawira** [comment]
Hello, sorry for the delay.  
This will take some time since I based all the update script on html parsing, I will work on it this month.  
Thank you for reporting :)

**Comment by jawira** [comment]
Hi, I don't think it's possible to use `emoji-sequences.txt`. 

For example zodiac signs, all 12 signs are represented as a range `2648..2653` so sign names are not available.

```
2648..2653  ; Basic_Emoji   ; Aries            # E0.6  [12] (♈..♓)
```

I'm open to any suggestion or alternative :)

**Comment by PaulWoitaschek** [comment]
You can use this and only use the fully qualified ones.
https://unicode.org/Public/emoji/15.0/emoji-test.txt

**Comment by jawira** [comment]
Hello, I worked on this in PR #21 , could you please check if Emoji class is ok for you?
After that I will merge the PR and release v15.0.1
