### ISSUE TITLE
Avoid distributing comments

### ISSUE THREAD

**Issue by szepeviktor** [jawira/emoji-catalog#8]
Hello 👋 
PHP OPcache stores comments in memory.
Please consider distributing a version stripped from comments and new lines.
A development version could live in another directory and being excluded from Packagist.
Thanks.

**Comment by jawira** [comment]
Is performance impacted due to comments? I added _docblocks_ because when you type <kbd>ctrl</kbd>+<kbd>q</kbd> in _PhpStorm_ you get nice documentation :P

![Screenshot from 2020-09-16 17-27-47](https://user-images.githubusercontent.com/496541/93359010-6daff700-f842-11ea-9179-31cb3d684c9e.png)

**Comment by szepeviktor** [comment]
I see!
No docblox, no help for devs.

**Comment by szepeviktor** [comment]
@jawira Would it be this?

https://github.com/szepeviktor/emoji-catalog/commit/c1486946eeb876b6e62ac5ee030e28b57a9efc1c

**Comment by jawira** [comment]
Yes! 👍 It should work if you remove that code.

**Comment by szepeviktor** [comment]
Thank you.

**Comment by szepeviktor** [comment]
@jawira It would be a heavy burden on me to follow your project and release everything in a compressed version.

Please reconsider adding a new EmojiCompressed class without indentation, spaces and docblocks.
Thank you!

**Comment by jawira** [comment]
Well, I'm not against the idea of removing the comments, but I just want to understand what the problem is. How the size of Emoji.php class is a problem for you? Can you explain please?

**Comment by szepeviktor** [comment]
Yes!
PHP production environments store source code as _byte code_ in OPcache.
`opcache.save_comments` is almost always enabled because modern frameworks heavily rely on Reflections.
So a half megabyte Emoji.php will sit in OPcache memory with 360 KB of comments that cannot be used at run-time.

**Comment by szepeviktor** [comment]
I know - I know: many projects have very little difference between development environment and production.

**Comment by szepeviktor** [comment]
Please see this **dirty** 💩 work-around: `php -w Emoji.php >EmojiCompressed.php`

```
-rw-r--r-- 1 viktor viktor 147327 Sep 16 17:28 EmojiCompressed.php
-rw-r--r-- 1 viktor viktor 478944 Sep 16 17:27 Emoji.php
```

**Comment by szepeviktor** [comment]
I'd be very-very sad 😿 if you'd focus 💯% on developers and 0️⃣% on companies.

**Comment by jawira** [comment]
Lol, you convinced me using emojis. I will work on this soon, next week max.

**Comment by jawira** [comment]
Done! It went from 468K to 157K. You can update to v2.0.1
